### Fetch all tasks

GET http://localhost:3000/tasks
Content-Type: application/json

POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title":"hello from china",
    "date":"2025-03-01T13:00:00Z",
    "description":"hello from nepalese from nepal",
    "priority":"low",
    "status":"Todo"
}

PUT http://localhost:3000/tasks
Content-Type:application/json

{
    "id":"1",
    "status":"InProgress"
}